-- 字典
CREATE TABLE SYS_DICT (
  DICT_ID BIGINT NOT NULL,
  DICT_TYPE BIGINT NOT NULL,
  DICT_NAME VARCHAR(100) NOT NULL,
  DICT_ORDER BIGINT NOT NULL DEFAULT 0,
  DICT_ENABLE TINYINT(1) NOT NULL DEFAULT 1,
  DICT_NOTE VARCHAR(200),
  PRIMARY KEY (DICT_ID));

-- 字典项
CREATE TABLE SYS_DICT_OPT (
  DICT_ID BIGINT NOT NULL,
  DICT_OPT_ID BIGINT NOT NULL, 
  DICT_OPT_NAME VARCHAR(100) NOT NULL,
  DICT_OPT_CODE VARCHAR(100),
  DICT_OPT_ORDER BIGINT NOT NULL DEFAULT 0,
  DICT_OPT_ENABLE TINYINT(1) NOT NULL DEFAULT 1,
  DICT_OPT_NOTE VARCHAR(200),
  PRIMARY KEY (DICT_ID,DICT_OPT_ID));

-- 部门
CREATE TABLE SYS_DPT (
  DPT_ID BIGINT NOT NULL AUTO_INCREMENT,
  DPT_PID BIGINT NOT NULL DEFAULT 0,
  DPT_NAME VARCHAR(100) NOT NULL,
  DPT_CODE VARCHAR(100),
  DPT_PHONE VARCHAR(100),
  DPT_ADDR VARCHAR(100),
  DPT_ORDER VARCHAR(200) NOT NULL,
  DPT_ENABLE TINYINT(1) NOT NULL DEFAULT 1,
  DPT_NOTE VARCHAR(200),
  PRIMARY KEY (DPT_ID))
  AUTO_INCREMENT=1000000;

CREATE TABLE SYS_DPT_LOG (
  LOG_ID BIGINT NOT NULL AUTO_INCREMENT,
  LOG_TYPE VARCHAR(100) NOT NULL,
  LOG_TIME DATETIME(3) NOT NULL,
  LOG_USER VARCHAR(100),
  DPT_ID BIGINT NOT NULL,
  DPT_PID BIGINT NOT NULL DEFAULT 0,
  DPT_NAME VARCHAR(100) NOT NULL,
  DPT_CODE VARCHAR(100),
  DPT_PHONE VARCHAR(100),
  DPT_ADDR VARCHAR(100),
  DPT_ORDER VARCHAR(200) NOT NULL,
  DPT_ENABLE TINYINT(1) NOT NULL DEFAULT 1,
  DPT_NOTE VARCHAR(200),
  PRIMARY KEY (LOG_ID))
  AUTO_INCREMENT=1000000;

-- 用户
CREATE TABLE SYS_USER (
  USER_ID BIGINT NOT NULL AUTO_INCREMENT,
  DPT_ID BIGINT NOT NULL DEFAULT 0,
  USERNAME VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  USER_NAME VARCHAR(100) NOT NULL,
  USER_CARD VARCHAR(100),
  USER_CODE VARCHAR(100),
  USER_TITLE VARCHAR(100),
  USER_GENDER TINYINT(1) NOT NULL DEFAULT 0,
  USER_BIRTHDAY DATETIME(3),
  USER_EMAIL VARCHAR(100),
  USER_PHONE VARCHAR(100),
  USER_ADDR VARCHAR(100),
  USER_CREATE_TIME DATETIME(3),
  USER_UPDATE_TIME DATETIME(3),
  USER_ENABLE TINYINT(1) NOT NULL DEFAULT 1,
  USER_NOTE VARCHAR(200),
  PRIMARY KEY (USER_ID))
  AUTO_INCREMENT=1000000;

CREATE TABLE SYS_USER_LOG (
  LOG_ID BIGINT NOT NULL AUTO_INCREMENT,
  LOG_TYPE VARCHAR(100) NOT NULL,
  LOG_TIME DATETIME(3) NOT NULL,
  LOG_USER VARCHAR(100),
  USER_ID BIGINT NOT NULL,
  DPT_ID BIGINT NOT NULL DEFAULT 0,
  USERNAME VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  USER_NAME VARCHAR(100) NOT NULL,
  USER_CARD VARCHAR(100),
  USER_CODE VARCHAR(100),
  USER_TITLE VARCHAR(100),
  USER_GENDER TINYINT(1) NOT NULL DEFAULT 0,
  USER_BIRTHDAY DATETIME(3),
  USER_EMAIL VARCHAR(100),
  USER_PHONE VARCHAR(100),
  USER_ADDR VARCHAR(100),
  USER_CREATE_TIME DATETIME(3),
  USER_UPDATE_TIME DATETIME(3),
  USER_ENABLE TINYINT(1) NOT NULL DEFAULT 1,
  USER_NOTE VARCHAR(200),
  PRIMARY KEY (LOG_ID))
  AUTO_INCREMENT=1000000;

-- 菜单
CREATE TABLE SYS_MENU (
  MENU_ID BIGINT NOT NULL AUTO_INCREMENT,
  MENU_PID BIGINT NOT NULL DEFAULT 0,
  MENU_NAME VARCHAR(100) NOT NULL,
  MENU_URL VARCHAR(100),
  MENU_MAT_ICON VARCHAR(100),
  MENU_ANTD_ICON VARCHAR(100),
  MENU_ANTD_ICON_THEME VARCHAR(100),
  MENU_ANTD_ICON_TWOTONE VARCHAR(100),
  MENU_ORDER VARCHAR(200) NOT NULL,
  MENU_ENABLE TINYINT(1) NOT NULL DEFAULT 1,
  MENU_NOTE VARCHAR(200),
  PRIMARY KEY (MENU_ID))
  AUTO_INCREMENT=1000000;

CREATE TABLE SYS_MENU_LOG (
  LOG_ID BIGINT NOT NULL AUTO_INCREMENT,
  LOG_TYPE VARCHAR(100) NOT NULL,
  LOG_TIME DATETIME(3) NOT NULL,
  LOG_USER VARCHAR(100),
  MENU_ID BIGINT NOT NULL,
  MENU_PID BIGINT NOT NULL DEFAULT 0,
  MENU_NAME VARCHAR(100) NOT NULL,
  MENU_URL VARCHAR(100),
  MENU_MAT_ICON VARCHAR(100),
  MENU_ANTD_ICON VARCHAR(100),
  MENU_ANTD_ICON_THEME VARCHAR(100),
  MENU_ANTD_ICON_TWOTONE VARCHAR(100),
  MENU_ORDER VARCHAR(200) NOT NULL,
  MENU_ENABLE TINYINT(1) NOT NULL DEFAULT 1,
  MENU_NOTE VARCHAR(200),
  PRIMARY KEY (LOG_ID))
  AUTO_INCREMENT=1000000;

-- 角色
CREATE TABLE SYS_ROLE (
  ROLE_ID BIGINT NOT NULL AUTO_INCREMENT,
  ROLE_NAME VARCHAR(100) NOT NULL,
  ROLE_CODE VARCHAR(100),
  ROLE_ORDER BIGINT NOT NULL DEFAULT 0,
  ROLE_ENABLE TINYINT(1) NOT NULL DEFAULT 1,
  ROLE_NOTE VARCHAR(100),
  PRIMARY KEY (ROLE_ID))
  AUTO_INCREMENT=1000000;

CREATE TABLE SYS_ROLE_LOG (
  LOG_ID BIGINT NOT NULL AUTO_INCREMENT,
  LOG_TYPE VARCHAR(100) NOT NULL,
  LOG_TIME DATETIME(3) NOT NULL,
  LOG_USER VARCHAR(100),
  ROLE_ID BIGINT NOT NULL,
  ROLE_NAME VARCHAR(100) NOT NULL,
  ROLE_CODE VARCHAR(100),
  ROLE_ORDER BIGINT NOT NULL DEFAULT 0,
  ROLE_ENABLE TINYINT(1) NOT NULL DEFAULT 1,
  ROLE_NOTE VARCHAR(100),
  PRIMARY KEY (LOG_ID))
  AUTO_INCREMENT=1000000;

-- 角色菜单
CREATE TABLE SYS_ROLE_MENU (
  ROLE_ID BIGINT NOT NULL,
  MENU_ID BIGINT NOT NULL,
  PRIMARY KEY (ROLE_ID,MENU_ID));

-- 角色用户
CREATE TABLE SYS_ROLE_USER (
  ROLE_ID BIGINT NOT NULL,
  USER_ID BIGINT NOT NULL,
  PRIMARY KEY (ROLE_ID,USER_ID));

-- 通知
CREATE TABLE SYS_NOTICE (
  NOTICE_ID BIGINT NOT NULL AUTO_INCREMENT,
  NOTICE_TITLE VARCHAR(100) NOT NULL,
  NOTICE_CONTENT VARCHAR(1000) NOT NULL,
  NOTICE_START_TIME DATETIME(3) NOT NULL,
  NOTICE_END_TIME DATETIME(3) NOT NULL,
  NOTICE_CREATE_TIME DATETIME(3),
  NOTICE_UPDATE_TIME DATETIME(3),
  PRIMARY KEY (NOTICE_ID))
  AUTO_INCREMENT=1000000;

CREATE TABLE SYS_NOTICE_LOG (
  LOG_ID BIGINT NOT NULL AUTO_INCREMENT,
  LOG_TYPE VARCHAR(100) NOT NULL,
  LOG_TIME DATETIME(3) NOT NULL,
  LOG_USER VARCHAR(100),
  NOTICE_ID BIGINT NOT NULL,
  NOTICE_TITLE VARCHAR(100) NOT NULL,
  NOTICE_CONTENT VARCHAR(1000),
  NOTICE_START_TIME DATETIME(3) NOT NULL,
  NOTICE_END_TIME DATETIME(3) NOT NULL,
  NOTICE_CREATE_TIME DATETIME(3),
  NOTICE_UPDATE_TIME DATETIME(3),
  PRIMARY KEY (LOG_ID))
  AUTO_INCREMENT=1000000;

-- 通知部门
CREATE TABLE SYS_NOTICE_DPT (
  NOTICE_ID BIGINT NOT NULL,
  DPT_ID BIGINT NOT NULL,
  PRIMARY KEY (NOTICE_ID,DPT_ID));

CREATE TABLE SYS_NOTICE_DPT_LOG (
  LOG_ID BIGINT NOT NULL,
  NOTICE_ID BIGINT NOT NULL,
  DPT_ID BIGINT NOT NULL,
  PRIMARY KEY (LOG_ID,NOTICE_ID,DPT_ID));

-- 访问日志
CREATE TABLE SYS_ACCESS_LOG (
  LOG_ID BIGINT NOT NULL AUTO_INCREMENT,
  LOG_ACCESS_TIME DATETIME(3) NOT NULL,
  LOG_ACCESS_IP VARCHAR(100) NOT NULL,
  LOG_ACCESS_USER VARCHAR(100),
  LOG_ACCESS_URI VARCHAR(200),
  LOG_ACCESS_UA VARCHAR(200),
  PRIMARY KEY (LOG_ID))
  AUTO_INCREMENT=1000000;

-- 索引
CREATE UNIQUE INDEX SYS_USER_IX1 ON SYS_USER (USERNAME);
