DROP TABLE SYS_DICT;
DROP TABLE SYS_DICT_OPT;

DROP TABLE SYS_DPT;
DROP TABLE SYS_DPT_LOG;

DROP TABLE SYS_USER;
DROP TABLE SYS_USER_LOG;

DROP TABLE SYS_MENU;
DROP TABLE SYS_MENU_LOG;

DROP TABLE SYS_ROLE;
DROP TABLE SYS_ROLE_LOG;
DROP TABLE SYS_ROLE_MENU;
DROP TABLE SYS_ROLE_USER;

DROP TABLE SYS_NOTICE;
DROP TABLE SYS_NOTICE_LOG;
DROP TABLE SYS_NOTICE_DPT;
DROP TABLE SYS_NOTICE_DPT_LOG;

DROP TABLE SYS_ACCESS_LOG;

DROP SEQUENCE SEQ_SYS_DPT;
DROP SEQUENCE SEQ_SYS_DPT_LOG;

DROP SEQUENCE SEQ_SYS_USER;
DROP SEQUENCE SEQ_SYS_USER_LOG;

DROP SEQUENCE SEQ_SYS_MENU;
DROP SEQUENCE SEQ_SYS_MENU_LOG;

DROP SEQUENCE SEQ_SYS_ROLE;
DROP SEQUENCE SEQ_SYS_ROLE_LOG;

DROP SEQUENCE SEQ_SYS_NOTICE;
DROP SEQUENCE SEQ_SYS_NOTICE_LOG;

DROP SEQUENCE SEQ_SYS_ACCESS_LOG;
