DROP TABLE IF EXISTS SYS_DICT;
DROP TABLE IF EXISTS SYS_DICT_OPT;

DROP TABLE IF EXISTS SYS_DPT;
DROP TABLE IF EXISTS SYS_DPT_LOG;

DROP TABLE IF EXISTS SYS_USER;
DROP TABLE IF EXISTS SYS_USER_LOG;

DROP TABLE IF EXISTS SYS_MENU;
DROP TABLE IF EXISTS SYS_MENU_LOG;

DROP TABLE IF EXISTS SYS_ROLE;
DROP TABLE IF EXISTS SYS_ROLE_LOG;
DROP TABLE IF EXISTS SYS_ROLE_MENU;
DROP TABLE IF EXISTS SYS_ROLE_USER;

DROP TABLE IF EXISTS SYS_NOTICE;
DROP TABLE IF EXISTS SYS_NOTICE_LOG;
DROP TABLE IF EXISTS SYS_NOTICE_DPT;
DROP TABLE IF EXISTS SYS_NOTICE_DPT_LOG;

DROP TABLE IF EXISTS SYS_ACCESS_LOG;
