CREATE SEQUENCE SEQ_SYS_DPT START WITH 1000000;
CREATE SEQUENCE SEQ_SYS_DPT_LOG START WITH 1000000;

CREATE SEQUENCE SEQ_SYS_USER START WITH 1000000;
CREATE SEQUENCE SEQ_SYS_USER_LOG START WITH 1000000;

CREATE SEQUENCE SEQ_SYS_MENU START WITH 1000000;
CREATE SEQUENCE SEQ_SYS_MENU_LOG START WITH 1000000;

CREATE SEQUENCE SEQ_SYS_ROLE START WITH 1000000;
CREATE SEQUENCE SEQ_SYS_ROLE_LOG START WITH 1000000;

CREATE SEQUENCE SEQ_SYS_NOTICE START WITH 1000000;
CREATE SEQUENCE SEQ_SYS_NOTICE_LOG START WITH 1000000;

-- 字典
CREATE TABLE SYS_DICT (
  DICT_ID NUMBER NOT NULL,
  DICT_TYPE NUMBER NOT NULL,
  DICT_NAME VARCHAR2(300) NOT NULL,
  DICT_ORDER NUMBER DEFAULT 0 NOT NULL,
  DICT_ENABLE NUMBER(1) DEFAULT 1 NOT NULL,
  DICT_NOTE VARCHAR2(600),
  PRIMARY KEY (DICT_ID));

-- 字典项
CREATE TABLE SYS_DICT_OPT (
  DICT_ID NUMBER NOT NULL,
  DICT_OPT_ID NUMBER NOT NULL,
  DICT_OPT_NAME VARCHAR2(300) NOT NULL,
  DICT_OPT_CODE VARCHAR2(300),
  DICT_OPT_ORDER NUMBER DEFAULT 0 NOT NULL,
  DICT_OPT_ENABLE NUMBER(1) DEFAULT 1 NOT NULL,
  DICT_OPT_NOTE VARCHAR2(600),
  PRIMARY KEY (DICT_ID,DICT_OPT_ID));

-- 部门
CREATE TABLE SYS_DPT (
  DPT_ID NUMBER NOT NULL,
  DPT_PID NUMBER DEFAULT 0 NOT NULL,
  DPT_NAME VARCHAR2(300) NOT NULL,
  DPT_CODE VARCHAR2(300),
  DPT_PHONE VARCHAR2(300),
  DPT_ADDR VARCHAR2(300),
  DPT_ORDER VARCHAR2(200) NOT NULL,
  DPT_ENABLE NUMBER(1) DEFAULT 1 NOT NULL,
  DPT_NOTE VARCHAR2(600),
  PRIMARY KEY (DPT_ID));

CREATE TABLE SYS_DPT_LOG (
  LOG_ID NUMBER NOT NULL,
  LOG_TYPE VARCHAR2(300) NOT NULL,
  LOG_TIME DATE NOT NULL,
  LOG_USER VARCHAR2(300),
  DPT_ID NUMBER NOT NULL,
  DPT_PID NUMBER DEFAULT 0 NOT NULL,
  DPT_NAME VARCHAR2(300) NOT NULL,
  DPT_CODE VARCHAR2(300),
  DPT_PHONE VARCHAR2(300),
  DPT_ADDR VARCHAR2(300),
  DPT_ORDER VARCHAR2(200) NOT NULL,
  DPT_ENABLE NUMBER(1) DEFAULT 1 NOT NULL,
  DPT_NOTE VARCHAR2(600),
  PRIMARY KEY (LOG_ID));

-- 用户
CREATE TABLE SYS_USER (
  USER_ID NUMBER NOT NULL,
  DPT_ID NUMBER DEFAULT 0 NOT NULL,
  USERNAME VARCHAR2(300) NOT NULL,
  PASSWORD VARCHAR2(300) NOT NULL,
  USER_NAME VARCHAR2(300) NOT NULL,
  USER_CARD VARCHAR2(300),
  USER_CODE VARCHAR2(300),
  USER_TITLE VARCHAR2(300),
  USER_GENDER NUMBER(1) DEFAULT 0 NOT NULL,
  USER_BIRTHDAY DATE,
  USER_EMAIL VARCHAR2(300),
  USER_PHONE VARCHAR2(300),
  USER_ADDR VARCHAR2(300),
  USER_CREATE_TIME DATE,
  USER_UPDATE_TIME DATE,
  USER_ENABLE NUMBER(1) DEFAULT 1 NOT NULL,
  USER_NOTE VARCHAR2(600),
  PRIMARY KEY (USER_ID));

CREATE TABLE SYS_USER_LOG (
  LOG_ID NUMBER NOT NULL,
  LOG_TYPE VARCHAR2(300) NOT NULL,
  LOG_TIME DATE NOT NULL,
  LOG_USER VARCHAR2(300),
  USER_ID NUMBER NOT NULL,
  DPT_ID NUMBER DEFAULT 0 NOT NULL,
  USERNAME VARCHAR2(300) NOT NULL,
  PASSWORD VARCHAR2(300) NOT NULL,
  USER_NAME VARCHAR2(300) NOT NULL,
  USER_CARD VARCHAR2(300),
  USER_CODE VARCHAR2(300),
  USER_TITLE VARCHAR2(300),
  USER_GENDER NUMBER(1) DEFAULT 0 NOT NULL,
  USER_BIRTHDAY DATE,
  USER_EMAIL VARCHAR2(300),
  USER_PHONE VARCHAR2(300),
  USER_ADDR VARCHAR2(300),
  USER_CREATE_TIME DATE,
  USER_UPDATE_TIME DATE,
  USER_ENABLE NUMBER(1) DEFAULT 1 NOT NULL,
  USER_NOTE VARCHAR2(600),
  PRIMARY KEY (LOG_ID));

-- 菜单
CREATE TABLE SYS_MENU (
  MENU_ID NUMBER NOT NULL,
  MENU_PID NUMBER DEFAULT 0 NOT NULL,
  MENU_NAME VARCHAR2(300) NOT NULL,
  MENU_URL VARCHAR2(300),
  MENU_MAT_ICON VARCHAR2(300),
  MENU_ANTD_ICON VARCHAR2(300),
  MENU_ANTD_ICON_THEME VARCHAR2(300),
  MENU_ANTD_ICON_TWOTONE VARCHAR2(300),
  MENU_ORDER VARCHAR2(200) NOT NULL,
  MENU_ENABLE NUMBER(1) DEFAULT 1 NOT NULL,
  MENU_NOTE VARCHAR2(600),
  PRIMARY KEY (MENU_ID));

CREATE TABLE SYS_MENU_LOG (
  LOG_ID NUMBER NOT NULL,
  LOG_TYPE VARCHAR2(300) NOT NULL,
  LOG_TIME DATE NOT NULL,
  LOG_USER VARCHAR2(300),
  MENU_ID NUMBER NOT NULL,
  MENU_PID NUMBER DEFAULT 0 NOT NULL,
  MENU_NAME VARCHAR2(300) NOT NULL,
  MENU_URL VARCHAR2(300),
  MENU_MAT_ICON VARCHAR2(300),
  MENU_ANTD_ICON VARCHAR2(300),
  MENU_ANTD_ICON_THEME VARCHAR2(300),
  MENU_ANTD_ICON_TWOTONE VARCHAR2(300),
  MENU_ORDER VARCHAR2(200) NOT NULL,
  MENU_ENABLE NUMBER(1) DEFAULT 1 NOT NULL,
  MENU_NOTE VARCHAR2(600),
  PRIMARY KEY (LOG_ID));

-- 角色
CREATE TABLE SYS_ROLE (
  ROLE_ID NUMBER NOT NULL,
  ROLE_NAME VARCHAR2(300) NOT NULL,
  ROLE_CODE VARCHAR2(300),
  ROLE_ORDER NUMBER DEFAULT 0 NOT NULL,
  ROLE_ENABLE NUMBER(1) DEFAULT 1 NOT NULL,
  ROLE_NOTE VARCHAR2(600),
  PRIMARY KEY (ROLE_ID));

CREATE TABLE SYS_ROLE_LOG (
  LOG_ID NUMBER NOT NULL,
  LOG_TYPE VARCHAR2(300) NOT NULL,
  LOG_TIME DATE NOT NULL,
  LOG_USER VARCHAR2(300),
  ROLE_ID NUMBER NOT NULL,
  ROLE_NAME VARCHAR2(300) NOT NULL,
  ROLE_CODE VARCHAR2(300),
  ROLE_ORDER NUMBER DEFAULT 0 NOT NULL,
  ROLE_ENABLE NUMBER(1) DEFAULT 1 NOT NULL,
  ROLE_NOTE VARCHAR2(600),
  PRIMARY KEY (LOG_ID));

-- 角色菜单
CREATE TABLE SYS_ROLE_MENU (
  ROLE_ID NUMBER NOT NULL,
  MENU_ID NUMBER NOT NULL,
  PRIMARY KEY (ROLE_ID,MENU_ID));

-- 角色用户
CREATE TABLE SYS_ROLE_USER (
  ROLE_ID NUMBER NOT NULL,
  USER_ID NUMBER NOT NULL,
  PRIMARY KEY (ROLE_ID,USER_ID));

-- 通知
CREATE TABLE SYS_NOTICE (
  NOTICE_ID NUMBER NOT NULL,
  NOTICE_TITLE VARCHAR2(300) NOT NULL,
  NOTICE_CONTENT VARCHAR2(4000),
  NOTICE_START_TIME DATE NOT NULL,
  NOTICE_END_TIME DATE NOT NULL,
  NOTICE_CREATE_TIME DATE,
  NOTICE_UPDATE_TIME DATE,
  PRIMARY KEY (NOTICE_ID));

CREATE TABLE SYS_NOTICE_LOG (
  LOG_ID NUMBER NOT NULL,
  LOG_TYPE VARCHAR2(300) NOT NULL,
  LOG_TIME DATE NOT NULL,
  LOG_USER VARCHAR2(300),
  NOTICE_ID NUMBER NOT NULL,
  NOTICE_TITLE VARCHAR2(300) NOT NULL,
  NOTICE_CONTENT VARCHAR2(4000),
  NOTICE_START_TIME DATE NOT NULL,
  NOTICE_END_TIME DATE NOT NULL,
  NOTICE_CREATE_TIME DATE,
  NOTICE_UPDATE_TIME DATE,
  PRIMARY KEY (LOG_ID));

-- 通知部门
CREATE TABLE SYS_NOTICE_DPT (
  NOTICE_ID NUMBER NOT NULL,
  DPT_ID NUMBER NOT NULL,
  PRIMARY KEY (NOTICE_ID,DPT_ID));

CREATE TABLE SYS_NOTICE_DPT_LOG (
  LOG_ID NUMBER NOT NULL,
  NOTICE_ID NUMBER NOT NULL,
  DPT_ID NUMBER NOT NULL,
  PRIMARY KEY (LOG_ID,NOTICE_ID,DPT_ID));

-- 访问日志
CREATE TABLE SYS_ACCESS_LOG (
  LOG_ID BIGINT NOT NULL,
  LOG_ACCESS_TIME DATE NOT NULL,
  LOG_ACCESS_IP VARCHAR(300) NOT NULL,
  LOG_ACCESS_USER VARCHAR(300),
  LOG_ACCESS_URI VARCHAR(600),
  LOG_ACCESS_UA VARCHAR(600),
  PRIMARY KEY (LOG_ID));

-- 索引
CREATE UNIQUE INDEX SYS_USER_IX1 ON SYS_USER (USERNAME);
