DROP TABLE IF EXISTS SYS_DICT;
DROP TABLE IF EXISTS SYS_DICT_OPT;

DROP TABLE IF EXISTS SYS_DPT;
DROP TABLE IF EXISTS SYS_DPT_LOG;

DROP TABLE IF EXISTS SYS_USER;
DROP TABLE IF EXISTS SYS_USER_LOG;

DROP TABLE IF EXISTS SYS_MENU;
DROP TABLE IF EXISTS SYS_MENU_LOG;

DROP TABLE IF EXISTS SYS_ROLE;
DROP TABLE IF EXISTS SYS_ROLE_LOG;
DROP TABLE IF EXISTS SYS_ROLE_MENU;
DROP TABLE IF EXISTS SYS_ROLE_USER;

DROP TABLE IF EXISTS SYS_NOTICE;
DROP TABLE IF EXISTS SYS_NOTICE_LOG;
DROP TABLE IF EXISTS SYS_NOTICE_DPT;
DROP TABLE IF EXISTS SYS_NOTICE_DPT_LOG;

DROP TABLE IF EXISTS SYS_ACCESS_LOG;

DROP SEQUENCE IF EXISTS SEQ_SYS_DPT;
DROP SEQUENCE IF EXISTS SEQ_SYS_DPT_LOG;

DROP SEQUENCE IF EXISTS SEQ_SYS_USER;
DROP SEQUENCE IF EXISTS SEQ_SYS_USER_LOG;

DROP SEQUENCE IF EXISTS SEQ_SYS_MENU;
DROP SEQUENCE IF EXISTS SEQ_SYS_MENU_LOG;

DROP SEQUENCE IF EXISTS SEQ_SYS_ROLE;
DROP SEQUENCE IF EXISTS SEQ_SYS_ROLE_LOG;

DROP SEQUENCE IF EXISTS SEQ_SYS_NOTICE;
DROP SEQUENCE IF EXISTS SEQ_SYS_NOTICE_LOG;

DROP SEQUENCE IF EXISTS SEQ_SYS_ACCESS_LOG;
