spring:
  datasource:
    platform: oracle
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.19:1521:orcl
    username: myabc
    password: myabc
    schema: classpath:db/schema-oracle.sql
    data: classpath:db/data.sql
    initialization-mode: never
    continue-on-error: true
